[buildPlans.Iolevka]
family = "Iolevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.Iolevka.variants]
  inherits = "ss08"

    [buildPlans.Iolevka.variants.design]
    capital-i = "serifed"
    capital-j = "flat-hook-serifed"
    capital-q = "crossing-baseline"
    capital-w = "straight-vertical-sides-serifless"
    capital-z = "straight-serifed"
    a = "double-storey-tailed"
    b = "toothless-corner-serifless"
    d = "tailed-serifed"
    f = "flat-hook-serifed"
    g = "double-storey-open"
    j = "flat-hook-serifed"
    l = "serifed-semi-tailed"
    m = "short-leg-top-left-and-bottom-right-serifed"
    q = "straight-bottom-serifed"
    r = "hookless-serifed"
    t = "flat-hook-short-neck"
    u = "toothless-corner-serifless"
    zero = "dotted"
    one = "base"
    three = "flat-top"
    four = "open-non-crossing"
    seven = "curly-serifless-crossbar"
    punctuation-dot = "square"
    tilde = "high"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    ampersand = "et-tailed"
    at = "threefold-tall"
    question = "corner-flat-hooked"

    [buildPlans.Iolevka.variants.italic]
    capital-i = "serifed"
    capital-j = "flat-hook-serifed"
    capital-q = "crossing-baseline"
    capital-w = "straight-vertical-sides-serifless"
    a = "double-storey-tailed"
    b = "toothless-corner-serifless"
    d = "tailed-serifed"
    e = "rounded"
    f = "flat-hook-diagonal-tailed"
    g = "single-storey-serifless"
    i = "serifed-diagonal-tailed"
    j = "diagonal-tailed-serifed"
    l = "serifed-diagonal-tailed"
    m = "short-leg-top-left-and-bottom-right-serifed"
    q = "straight-bottom-serifed"
    r = "hookless-serifed"
    t = "diagonal-tailed"
    u = "toothless-corner-serifless"
    y = "cursive-serifless"
    zero = "dotted"
    one = "base"
    two = "curly-neck"
    three = "flat-top"
    four = "open-non-crossing"
    punctuation-dot = "square"
    tilde = "high"
    paren = "flat-arc"
    brace = "curly-flat-boundary"
    guillemet = "curly"
    number-sign = "upright"
    at = "threefold-tall"
    question = "corner-flat-hooked"
    pilcrow = "low"
    micro-sign = "toothed-serifless"
    lig-double-arrow-bar = "without-notch"

[buildPlans.Iolevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Iolevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Iolevka.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.Iolevka.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.Iolevka.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Iolevka.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.Iolevka.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"